import React from 'react';
import { ScrollView, Text, View } from 'react-native';
import { content } from '../src/content/index.ts';
import { contractProgressPercent } from '../src/game/contracts.ts';
import type { GameState } from '../src/game/state.ts';
import { estimateTrainerDifficulty, trainerRelationshipTier } from '../src/systems/trainers.ts';
import { Button, Panel, Portrait, StatusChip, s } from './ui';
import { ItemStrip } from './ItemVisuals';
import { speciesName, type Confirm } from './screens';
import { CREST_GUARDIANS, crestGuardianBondEligibility } from '../src/content/crest-guardians.ts';
import { CardArt } from './CardArt';

const objectiveLabel=(event:string,target?:string)=>event==='complete-expedition'?`Complete ${content.zones.find(zone=>zone.id===target)?.name??target}`:event==='capture-species'?`Capture ${speciesName(target??'')} specimens`:event==='defeat-boss'?'Defeat an expedition boss':'Complete a monster sale';

export function ContractsScreen({state,confirm}:{state:GameState;confirm:Confirm}) {
  const occupied=state.contracts.filter(contract=>contract.status==='active'||contract.status==='complete').length;
  return <ScrollView contentContainerStyle={s.content}><Text style={s.eyebrow}>CITY BOARD / CONTRACTS</Text><Text accessibilityRole="header" style={s.title}>Keeper commissions</Text><Panel><View style={s.row}><StatusChip label={`${occupied}/3 accepted`} tone={occupied<3?'good':'warn'}/><StatusChip label={`Reputation ${state.player.reputation}`}/><StatusChip label={`Day ${state.world.day}`}/></View><Text style={s.muted}>Contracts progress through normal expeditions, captures, boss victories and completed Exchange sales. Expired commissions can be accepted again.</Text></Panel>
    {content.contracts.map(def=>{const entry=state.contracts.find(contract=>contract.definitionId===def.id),status=entry?.status??'available',progress=entry?.progress??0,percent=contractProgressPercent(progress,def.objective.required),locked=def.objective.event==='complete-expedition'&&!!def.objective.targetId&&!state.world.unlockedZoneIds.includes(def.objective.targetId),limit=occupied>=3&&!['active','complete'].includes(status);return <Panel key={def.id}><View style={[s.row,{justifyContent:'space-between'}]}><Text style={[s.subtitle,{flex:1}]}>{def.name}</Text><StatusChip label={status} tone={status==='complete'?'good':status==='active'?'warn':status==='expired'?'locked':'neutral'}/></View><Text style={s.text}>{def.description}</Text><Text style={s.muted}>{objectiveLabel(def.objective.event,def.objective.targetId)} · {progress}/{def.objective.required}</Text><View accessibilityLabel={`${percent} percent complete`} style={{height:8,backgroundColor:'#071923'}}><View style={{height:8,width:`${percent}%`,backgroundColor:status==='complete'?'#75a978':'#d4af59'}}/></View>{entry&&<Text style={s.muted}>Deadline: day {entry.expiresOnDay} · {Math.max(0,entry.expiresOnDay-state.world.day)} day(s) remaining</Text>}<View style={s.row}><StatusChip label={`${def.reward.crowns} Crowns`} tone="warn"/><StatusChip label={`${def.reward.reputation??0} reputation`}/></View>{def.reward.items&&<ItemStrip items={def.reward.items}/>}<Button title={status==='complete'?'Claim reward':status==='active'?'Abandon contract':locked?'Expedition locked':limit?'Contract limit reached':'Accept contract'} disabled={locked||limit} onPress={()=>confirm(status==='complete'?'Claim contract reward':status==='active'?'Abandon contract?':'Accept contract?',`${def.name}\n${def.description}`,{kind:status==='complete'?'contract-claim':status==='active'?'contract-abandon':'contract-accept',definitionId:def.id})}/></Panel>})}
  </ScrollView>;
}

export function ArenaScreen({state,confirm}:{state:GameState;confirm:Confirm}) {
  const last=state.world.dynamicState['arena:lastResult'];
  return <ScrollView contentContainerStyle={s.content}><Text style={s.eyebrow}>CITY ARENA / TRAINERS</Text><Text accessibilityRole="header" style={s.title}>Challenge hall</Text>{last&&<Panel><Text style={s.eyebrow}>LAST MATCH</Text><Text style={s.subtitle}>{String(last)}</Text><Text style={s.muted}>{Number(state.world.dynamicState['arena:lastTurns']??0)} turns · {Number(state.world.dynamicState['arena:lastReward']??0)} Crowns earned</Text></Panel>}<Panel><Text style={s.muted}>Trainer matches resolve using the production battle rules and your active team. Wounds persist, opponents train as days pass, and each trainer can be challenged once per day.</Text></Panel>
    {content.trainers.map(def=>{const trainer=state.trainers[def.id],difficulty=trainer?estimateTrainerDifficulty(state,def.id):'unranked',fought=trainer?.lastChallengeDay===state.world.day;return <Panel key={def.id}><View style={[s.row,{justifyContent:'space-between'}]}><View style={{flex:1}}><Text style={s.subtitle}>{def.name}</Text><Text style={s.muted}>{def.role} · {def.specialty}</Text></View><StatusChip label={trainer?trainerRelationshipTier(trainer.relationship):'new'} tone="good"/></View><Text style={s.text}>{def.description}</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:8}}>{def.teamSpeciesIds.map(id=><View key={id} style={{alignItems:'center',width:112}}><Portrait speciesId={id}/><Text style={s.muted}>{speciesName(id)}</Text></View>)}</ScrollView><View style={s.row}><StatusChip label={`Difficulty ${difficulty}`} tone={difficulty==='easy'?'good':difficulty==='severe'?'locked':'warn'}/><StatusChip label={`${def.challengeRewardCrowns} C reward`} tone="warn"/>{trainer&&<StatusChip label={`${trainer.losses} wins · ${trainer.wins} losses`}/>}</View><Button title={state.activeExpedition?'Return from expedition':fought?'Already challenged today':state.player.activeTeamIds.length?'Challenge trainer':'Choose an active team'} disabled={!!state.activeExpedition||fought||!state.player.activeTeamIds.length} onPress={()=>confirm(`Challenge ${def.name}?`,`Your active team will auto-battle ${def.name}. Damage persists after the match; victory awards ${def.challengeRewardCrowns} Crowns.`,{kind:'trainer-challenge',trainerId:def.id})}/></Panel>})}
  </ScrollView>;
}

export function SanctuaryScreen({state,confirm}:{state:GameState;confirm:Confirm}) {
  const research=Object.values(state.player.researchBySpecies).reduce((sum,item)=>sum+item.level,0),wins=state.player.monsterIds.reduce((sum,id)=>sum+(state.monsters[id]?.wins??0),0);
  return <ScrollView contentContainerStyle={s.content}><Text style={s.eyebrow}>HIDDEN SANCTUARIES / CREST GUARDIANS</Text><Text accessibilityRole="header" style={s.title}>The living scales</Text><Panel><Text style={s.text}>Crest Guardians are earned bonds, never ordinary catches, eggs, or market stock.</Text><View style={s.row}><StatusChip label={`Reputation ${state.player.reputation}`} tone="warn"/><StatusChip label={`Research levels ${research}`}/><StatusChip label={`Roster wins ${wins}`}/></View></Panel>{CREST_GUARDIANS.map(guardian=>{const check=crestGuardianBondEligibility(state,guardian.speciesId),requiredRegion=guardian.speciesId==='aurevine'?'greenreach':'stormpeak',here=state.player.location.regionId===requiredRegion,owned=state.player.monsterIds.some(id=>state.monsters[id]?.speciesId===guardian.speciesId);return <Panel key={guardian.speciesId}><Text style={s.eyebrow}>{guardian.title.toUpperCase()}</Text><Text style={s.subtitle}>{speciesName(guardian.speciesId)}</Text><View style={{alignItems:'center'}}><CardArt speciesId={guardian.speciesId} width={220}/></View><Text style={s.text}>{guardian.sanctuary}</Text><Text style={s.muted}>{guardian.visualConcept}</Text><View style={s.row}><StatusChip label={`${guardian.minimumReputation} reputation`} tone={state.player.reputation>=guardian.minimumReputation?'good':'locked'}/><StatusChip label={guardian.speciesId==='aurevine'?`${research}/12 research`:`${wins}/20 wins`} tone={(guardian.speciesId==='aurevine'?research>=12:wins>=20)?'good':'locked'}/><StatusChip label={here?'At sanctuary':`Travel to ${requiredRegion}`} tone={here?'good':'warn'}/></View>{!check.eligible&&<Text style={s.muted}>{check.reasons.join('\n')}</Text>}<Button title={owned?'Guardian already bonded':!here?'Wrong region':check.eligible?'Form the Crest bond':'Requirements incomplete'} disabled={owned||!here||!check.eligible} onPress={()=>confirm(`Bond with ${speciesName(guardian.speciesId)}?`,'This unique legendary joins your roster with its Crest variant and cannot be bonded twice.',{kind:'guardian-bond',speciesId:guardian.speciesId})}/></Panel>})}</ScrollView>;
}
