export const GAME_TYPES = [
  "normal", "fire", "water", "grass", "electric", "ice", "fighting", "poison",
  "ground", "flying", "psychic", "bug", "rock", "ghost", "dragon", "dark", "steel", "fairy",
]         ;

                                                   
                                                                      
                                           
                                               
                                           
                                                
                                                                           

                                       
                          
                               
                      
                        
                      
                            
                          
 

                                    
             
                                                                                                
                     
                                                                            
                    
                                                       
                        
               
                      
                         
                              
                          
                                        
                          
                 
                     
                   
                  
                               
                                                                                                    
                                    
                                    
                               
                                                                                   
                                    
                    
                          
                                  
                              
                          
                              
                
                                       
 

                          
                               
                     
 

                                    
             
                    
                    
           
                
             
               
                    
                              
                                   
                                      
                   
                    
                   
                    
               
               
                 
                                   
 

                                           
               
              
             
 
