// Generated by scripts/build-monster-card-assets.py. Do not edit by hand.
export const GENERATED_CARD_ASSETS = {
  "mossveil": {
    "internalId": 1,
    "cardAssetId": "monsterdex/cards/001--mossveil--card.png"
  },
  "canopyre": {
    "internalId": 2,
    "cardAssetId": "monsterdex/cards/002--canopyre--card.png"
  },
  "voltgrazer": {
    "internalId": 3,
    "cardAssetId": "monsterdex/cards/003--voltgrazer--card.png"
  },
  "tempestride": {
    "internalId": 4,
    "cardAssetId": "monsterdex/cards/004--tempestride--card.png"
  },
  "cindlet": {
    "internalId": 5,
    "cardAssetId": "monsterdex/cards/005--cindlet--card.png"
  },
  "kilnback": {
    "internalId": 6,
    "cardAssetId": "monsterdex/cards/006--kilnback--card.png"
  },
  "pyroclastor": {
    "internalId": 7,
    "cardAssetId": "monsterdex/cards/007--pyroclastor--card.png"
  },
  "rifflin": {
    "internalId": 8,
    "cardAssetId": "monsterdex/cards/008--rifflin--card.png"
  },
  "brineveil": {
    "internalId": 9,
    "cardAssetId": "monsterdex/cards/009--brineveil--card.png"
  },
  "budmote": {
    "internalId": 10,
    "cardAssetId": "monsterdex/cards/010--budmote--card.png"
  },
  "crownbloom": {
    "internalId": 11,
    "cardAssetId": "monsterdex/cards/011--crownbloom--card.png"
  },
  "pebblit": {
    "internalId": 12,
    "cardAssetId": "monsterdex/cards/012--pebblit--card.png"
  },
  "cairnox": {
    "internalId": 13,
    "cardAssetId": "monsterdex/cards/013--cairnox--card.png"
  },
  "gloamkit": {
    "internalId": 14,
    "cardAssetId": "monsterdex/cards/014--gloamkit--card.png"
  },
  "nocturnyx": {
    "internalId": 15,
    "cardAssetId": "monsterdex/cards/015--nocturnyx--card.png"
  },
  "fuzzvolt": {
    "internalId": 16,
    "cardAssetId": "monsterdex/cards/016--fuzzvolt--card.png"
  },
  "loomspark": {
    "internalId": 17,
    "cardAssetId": "monsterdex/cards/017--loomspark--card.png"
  },
  "mucklet": {
    "internalId": 18,
    "cardAssetId": "monsterdex/cards/018--mucklet--card.png"
  },
  "bogrumbler": {
    "internalId": 19,
    "cardAssetId": "monsterdex/cards/019--bogrumbler--card.png"
  },
  "chimeshell": {
    "internalId": 20,
    "cardAssetId": "monsterdex/cards/020--chimeshell--card.png"
  },
  "ashwing": {
    "internalId": 21,
    "cardAssetId": "monsterdex/cards/021--ashwing--card.png"
  },
  "solvulture": {
    "internalId": 22,
    "cardAssetId": "monsterdex/cards/022--solvulture--card.png"
  },
  "frostuft": {
    "internalId": 23,
    "cardAssetId": "monsterdex/cards/023--frostuft--card.png"
  },
  "rimehorn": {
    "internalId": 24,
    "cardAssetId": "monsterdex/cards/024--rimehorn--card.png"
  },
  "gleamgulper": {
    "internalId": 25,
    "cardAssetId": "monsterdex/cards/025--gleamgulper--card.png"
  },
  "ferricrawl": {
    "internalId": 26,
    "cardAssetId": "monsterdex/cards/026--ferricrawl--card.png"
  },
  "bastionsect": {
    "internalId": 27,
    "cardAssetId": "monsterdex/cards/027--bastionsect--card.png"
  },
  "wispling": {
    "internalId": 28,
    "cardAssetId": "monsterdex/cards/028--wispling--card.png"
  },
  "mournglade": {
    "internalId": 29,
    "cardAssetId": "monsterdex/cards/029--mournglade--card.png"
  },
  "skyrill": {
    "internalId": 30,
    "cardAssetId": "monsterdex/cards/030--skyrill--card.png"
  },
  "galecrest": {
    "internalId": 31,
    "cardAssetId": "monsterdex/cards/031--galecrest--card.png"
  },
  "dunelet": {
    "internalId": 32,
    "cardAssetId": "monsterdex/cards/032--dunelet--card.png"
  },
  "mirrormaw": {
    "internalId": 33,
    "cardAssetId": "monsterdex/cards/033--mirrormaw--card.png"
  },
  "vialtail": {
    "internalId": 34,
    "cardAssetId": "monsterdex/cards/034--vialtail--card.png"
  },
  "runebuck": {
    "internalId": 35,
    "cardAssetId": "monsterdex/cards/035--runebuck--card.png"
  },
  "deepmaw": {
    "internalId": 36,
    "cardAssetId": "monsterdex/cards/036--deepmaw--card.png"
  },
  "prismite": {
    "internalId": 37,
    "cardAssetId": "monsterdex/cards/037--prismite--card.png"
  },
  "cloudrum": {
    "internalId": 38,
    "cardAssetId": "monsterdex/cards/038--cloudrum--card.png"
  },
  "oathcoil": {
    "internalId": 39,
    "cardAssetId": "monsterdex/cards/039--oathcoil--card.png"
  },
  "riftwarden": {
    "internalId": 40,
    "cardAssetId": "monsterdex/cards/040--riftwarden--card.png"
  },
  "glintad": {
    "internalId": 41,
    "cardAssetId": "monsterdex/cards/041--glintad--card.png"
  },
  "facetoad": {
    "internalId": 42,
    "cardAssetId": "monsterdex/cards/042--facetoad--card.png"
  },
  "sootsnip": {
    "internalId": 43,
    "cardAssetId": "monsterdex/cards/043--sootsnip--card.png"
  },
  "cauterwing": {
    "internalId": 44,
    "cardAssetId": "monsterdex/cards/044--cauterwing--card.png"
  },
  "tidepup": {
    "internalId": 45,
    "cardAssetId": "monsterdex/cards/045--tidepup--card.png"
  },
  "reefhowl": {
    "internalId": 46,
    "cardAssetId": "monsterdex/cards/046--reefhowl--card.png"
  },
  "bramblejaw": {
    "internalId": 47,
    "cardAssetId": "monsterdex/cards/047--bramblejaw--card.png"
  },
  "thicketyr": {
    "internalId": 48,
    "cardAssetId": "monsterdex/cards/048--thicketyr--card.png"
  },
  "coilbud": {
    "internalId": 49,
    "cardAssetId": "monsterdex/cards/049--coilbud--card.png"
  },
  "dynamoira": {
    "internalId": 50,
    "cardAssetId": "monsterdex/cards/050--dynamoira--card.png"
  },
  "hushhare": {
    "internalId": 51,
    "cardAssetId": "monsterdex/cards/051--hushhare--card.png"
  },
  "pallop": {
    "internalId": 52,
    "cardAssetId": "monsterdex/cards/052--pallop--card.png"
  },
  "oreling": {
    "internalId": 53,
    "cardAssetId": "monsterdex/cards/053--oreling--card.png"
  },
  "magnox": {
    "internalId": 54,
    "cardAssetId": "monsterdex/cards/054--magnox--card.png"
  },
  "dustlet": {
    "internalId": 55,
    "cardAssetId": "monsterdex/cards/055--dustlet--card.png"
  },
  "siroccoil": {
    "internalId": 56,
    "cardAssetId": "monsterdex/cards/056--siroccoil--card.png"
  },
  "chillip": {
    "internalId": 57,
    "cardAssetId": "monsterdex/cards/057--chillip--card.png"
  },
  "crysalid": {
    "internalId": 58,
    "cardAssetId": "monsterdex/cards/058--crysalid--card.png"
  },
  "borealume": {
    "internalId": 59,
    "cardAssetId": "monsterdex/cards/059--borealume--card.png"
  },
  "knucklebud": {
    "internalId": 60,
    "cardAssetId": "monsterdex/cards/060--knucklebud--card.png"
  },
  "burlbrute": {
    "internalId": 61,
    "cardAssetId": "monsterdex/cards/061--burlbrute--card.png"
  },
  "pipscale": {
    "internalId": 62,
    "cardAssetId": "monsterdex/cards/062--pipscale--card.png"
  },
  "venodrake": {
    "internalId": 63,
    "cardAssetId": "monsterdex/cards/063--venodrake--card.png"
  },
  "whirloo": {
    "internalId": 64,
    "cardAssetId": "monsterdex/cards/064--whirloo--card.png"
  },
  "oracline": {
    "internalId": 65,
    "cardAssetId": "monsterdex/cards/065--oracline--card.png"
  },
  "clinkshade": {
    "internalId": 66,
    "cardAssetId": "monsterdex/cards/066--clinkshade--card.png"
  },
  "mirthmew": {
    "internalId": 67,
    "cardAssetId": "monsterdex/cards/067--mirthmew--card.png"
  },
  "siltwraith": {
    "internalId": 68,
    "cardAssetId": "monsterdex/cards/068--siltwraith--card.png"
  },
  "kitespine": {
    "internalId": 69,
    "cardAssetId": "monsterdex/cards/069--kitespine--card.png"
  },
  "tusslegrub": {
    "internalId": 70,
    "cardAssetId": "monsterdex/cards/070--tusslegrub--card.png"
  },
  "rooklimb": {
    "internalId": 71,
    "cardAssetId": "monsterdex/cards/071--rooklimb--card.png"
  },
  "drizzlepod": {
    "internalId": 72,
    "cardAssetId": "monsterdex/cards/072--drizzlepod--card.png"
  },
  "noxitide": {
    "internalId": 73,
    "cardAssetId": "monsterdex/cards/073--noxitide--card.png"
  },
  "hearthwish": {
    "internalId": 74,
    "cardAssetId": "monsterdex/cards/074--hearthwish--card.png"
  },
  "asterolith": {
    "internalId": 75,
    "cardAssetId": "monsterdex/cards/075--asterolith--card.png"
  },
  "coldforge": {
    "internalId": 76,
    "cardAssetId": "monsterdex/cards/076--coldforge--card.png"
  },
  "tumblet": {
    "internalId": 77,
    "cardAssetId": "monsterdex/cards/077--tumblet--card.png"
  },
  "glimmerguilt": {
    "internalId": 78,
    "cardAssetId": "monsterdex/cards/078--glimmerguilt--card.png"
  },
  "eonbriar": {
    "internalId": 79,
    "cardAssetId": "monsterdex/cards/079--eonbriar--card.png"
  },
  "resonuckle": {
    "internalId": 80,
    "cardAssetId": "monsterdex/cards/080--resonuckle--card.png"
  },
  "quillop": {
    "internalId": 81,
    "cardAssetId": "monsterdex/cards/081--quillop--card.png"
  },
  "scribetail": {
    "internalId": 82,
    "cardAssetId": "monsterdex/cards/082--scribetail--card.png"
  },
  "brinibble": {
    "internalId": 83,
    "cardAssetId": "monsterdex/cards/083--brinibble--card.png"
  },
  "steamvat": {
    "internalId": 84,
    "cardAssetId": "monsterdex/cards/084--steamvat--card.png"
  },
  "frondle": {
    "internalId": 85,
    "cardAssetId": "monsterdex/cards/085--frondle--card.png"
  },
  "thornloom": {
    "internalId": 86,
    "cardAssetId": "monsterdex/cards/086--thornloom--card.png"
  },
  "gravvel": {
    "internalId": 87,
    "cardAssetId": "monsterdex/cards/087--gravvel--card.png"
  },
  "faultusk": {
    "internalId": 88,
    "cardAssetId": "monsterdex/cards/088--faultusk--card.png"
  },
  "arcwren": {
    "internalId": 89,
    "cardAssetId": "monsterdex/cards/089--arcwren--card.png"
  },
  "stormscribe": {
    "internalId": 90,
    "cardAssetId": "monsterdex/cards/090--stormscribe--card.png"
  },
  "sprigbara": {
    "internalId": 91,
    "cardAssetId": "monsterdex/cards/091--sprigbara--card.png"
  },
  "fenbara": {
    "internalId": 92,
    "cardAssetId": "monsterdex/cards/092--fenbara--card.png"
  },
  "crownbara": {
    "internalId": 93,
    "cardAssetId": "monsterdex/cards/093--crownbara--card.png"
  },
  "prismink": {
    "internalId": 94,
    "cardAssetId": "monsterdex/cards/094--prismink--card.png"
  },
  "veilscale": {
    "internalId": 95,
    "cardAssetId": "monsterdex/cards/095--veilscale--card.png"
  },
  "chromavex": {
    "internalId": 96,
    "cardAssetId": "monsterdex/cards/096--chromavex--card.png"
  },
  "emberfin": {
    "internalId": 97,
    "cardAssetId": "monsterdex/cards/097--emberfin--card.png"
  },
  "anemflare": {
    "internalId": 98,
    "cardAssetId": "monsterdex/cards/098--anemflare--card.png"
  },
  "floelet": {
    "internalId": 99,
    "cardAssetId": "monsterdex/cards/099--floelet--card.png"
  },
  "regaldrift": {
    "internalId": 100,
    "cardAssetId": "monsterdex/cards/100--regaldrift--card.png"
  },
  "imperglace": {
    "internalId": 101,
    "cardAssetId": "monsterdex/cards/101--imperglace--card.png"
  },
  "drowseed": {
    "internalId": 102,
    "cardAssetId": "monsterdex/cards/102--drowseed--card.png"
  },
  "somnaloak": {
    "internalId": 103,
    "cardAssetId": "monsterdex/cards/103--somnaloak--card.png"
  },
  "cinderskink": {
    "internalId": 104,
    "cardAssetId": "monsterdex/cards/104--cinderskink--card.png"
  },
  "ashmaul": {
    "internalId": 105,
    "cardAssetId": "monsterdex/cards/105--ashmaul--card.png"
  },
  "vulcarodo": {
    "internalId": 106,
    "cardAssetId": "monsterdex/cards/106--vulcarodo--card.png"
  },
  "burrowseer": {
    "internalId": 107,
    "cardAssetId": "monsterdex/cards/107--burrowseer--card.png"
  },
  "sunoracle": {
    "internalId": 108,
    "cardAssetId": "monsterdex/cards/108--sunoracle--card.png"
  },
  "mossfist": {
    "internalId": 109,
    "cardAssetId": "monsterdex/cards/109--mossfist--card.png"
  },
  "grovegrip": {
    "internalId": 110,
    "cardAssetId": "monsterdex/cards/110--grovegrip--card.png"
  },
  "duskfang": {
    "internalId": 111,
    "cardAssetId": "monsterdex/cards/111--duskfang--card.png"
  },
  "umbraasp": {
    "internalId": 112,
    "cardAssetId": "monsterdex/cards/112--umbraasp--card.png"
  },
  "burrowarden": {
    "internalId": 113,
    "cardAssetId": "monsterdex/cards/113--burrowarden--card.png"
  },
  "aetherbale": {
    "internalId": 114,
    "cardAssetId": "monsterdex/cards/114--aetherbale--card.png"
  },
  "nightwake": {
    "internalId": 115,
    "cardAssetId": "monsterdex/cards/115--nightwake--card.png"
  },
  "stridepelt": {
    "internalId": 116,
    "cardAssetId": "monsterdex/cards/116--stridepelt--card.png"
  },
  "velocrest": {
    "internalId": 117,
    "cardAssetId": "monsterdex/cards/117--velocrest--card.png"
  },
  "stormpard": {
    "internalId": 118,
    "cardAssetId": "monsterdex/cards/118--stormpard--card.png"
  },
  "tundrusk": {
    "internalId": 119,
    "cardAssetId": "monsterdex/cards/119--tundrusk--card.png"
  },
  "paleolith": {
    "internalId": 120,
    "cardAssetId": "monsterdex/cards/120--paleolith--card.png"
  },
  "glacimast": {
    "internalId": 121,
    "cardAssetId": "monsterdex/cards/121--glacimast--card.png"
  },
  "reedblade": {
    "internalId": 122,
    "cardAssetId": "monsterdex/cards/122--reedblade--card.png"
  },
  "thornscythe": {
    "internalId": 123,
    "cardAssetId": "monsterdex/cards/123--thornscythe--card.png"
  },
  "ferramantis": {
    "internalId": 124,
    "cardAssetId": "monsterdex/cards/124--ferramantis--card.png"
  },
  "skydisc": {
    "internalId": 125,
    "cardAssetId": "monsterdex/cards/125--skydisc--card.png"
  },
  "aetheray": {
    "internalId": 126,
    "cardAssetId": "monsterdex/cards/126--aetheray--card.png"
  },
  "murmurwing": {
    "internalId": 127,
    "cardAssetId": "monsterdex/cards/127--murmurwing--card.png"
  },
  "echonoct": {
    "internalId": 128,
    "cardAssetId": "monsterdex/cards/128--echonoct--card.png"
  },
  "duneclasp": {
    "internalId": 129,
    "cardAssetId": "monsterdex/cards/129--duneclasp--card.png"
  },
  "cragsting": {
    "internalId": 130,
    "cardAssetId": "monsterdex/cards/130--cragsting--card.png"
  },
  "clawtide": {
    "internalId": 131,
    "cardAssetId": "monsterdex/cards/131--clawtide--card.png"
  },
  "pugilcrab": {
    "internalId": 132,
    "cardAssetId": "monsterdex/cards/132--pugilcrab--card.png"
  },
  "lumigill": {
    "internalId": 133,
    "cardAssetId": "monsterdex/cards/133--lumigill--card.png"
  },
  "faelotl": {
    "internalId": 134,
    "cardAssetId": "monsterdex/cards/134--faelotl--card.png"
  },
  "shardpang": {
    "internalId": 135,
    "cardAssetId": "monsterdex/cards/135--shardpang--card.png"
  },
  "ferrapine": {
    "internalId": 136,
    "cardAssetId": "monsterdex/cards/136--ferrapine--card.png"
  },
  "marshgrim": {
    "internalId": 137,
    "cardAssetId": "monsterdex/cards/137--marshgrim--card.png"
  },
  "riftjaw": {
    "internalId": 138,
    "cardAssetId": "monsterdex/cards/138--riftjaw--card.png"
  },
  "voltspur": {
    "internalId": 139,
    "cardAssetId": "monsterdex/cards/139--voltspur--card.png"
  },
  "razorcrest": {
    "internalId": 140,
    "cardAssetId": "monsterdex/cards/140--razorcrest--card.png"
  },
  "prismtail": {
    "internalId": 141,
    "cardAssetId": "monsterdex/cards/141--prismtail--card.png"
  },
  "mossdrowse": {
    "internalId": 142,
    "cardAssetId": "monsterdex/cards/142--mossdrowse--card.png"
  },
  "cacklemaw": {
    "internalId": 143,
    "cardAssetId": "monsterdex/cards/143--cacklemaw--card.png"
  },
  "sparkspine": {
    "internalId": 144,
    "cardAssetId": "monsterdex/cards/144--sparkspine--card.png"
  },
  "burrowbeak": {
    "internalId": 145,
    "cardAssetId": "monsterdex/cards/145--burrowbeak--card.png"
  },
  "wraithjelly": {
    "internalId": 146,
    "cardAssetId": "monsterdex/cards/146--wraithjelly--card.png"
  },
  "brinehorn": {
    "internalId": 147,
    "cardAssetId": "monsterdex/cards/147--brinehorn--card.png"
  },
  "aurorwhal": {
    "internalId": 148,
    "cardAssetId": "monsterdex/cards/148--aurorwhal--card.png"
  },
  "siltweb": {
    "internalId": 149,
    "cardAssetId": "monsterdex/cards/149--siltweb--card.png"
  },
  "cryptarach": {
    "internalId": 150,
    "cardAssetId": "monsterdex/cards/150--cryptarach--card.png"
  },
  "puffleece": {
    "internalId": 151,
    "cardAssetId": "monsterdex/cards/151--puffleece--card.png"
  },
  "loomstride": {
    "internalId": 152,
    "cardAssetId": "monsterdex/cards/152--loomstride--card.png"
  },
  "aurawool": {
    "internalId": 153,
    "cardAssetId": "monsterdex/cards/153--aurawool--card.png"
  },
  "craghush": {
    "internalId": 154,
    "cardAssetId": "monsterdex/cards/154--craghush--card.png"
  },
  "rimeclaw": {
    "internalId": 155,
    "cardAssetId": "monsterdex/cards/155--rimeclaw--card.png"
  },
  "whitewroth": {
    "internalId": 156,
    "cardAssetId": "monsterdex/cards/156--whitewroth--card.png"
  },
  "sickletoe": {
    "internalId": 157,
    "cardAssetId": "monsterdex/cards/157--sickletoe--card.png"
  },
  "quillrend": {
    "internalId": 158,
    "cardAssetId": "monsterdex/cards/158--quillrend--card.png"
  },
  "crescentyr": {
    "internalId": 159,
    "cardAssetId": "monsterdex/cards/159--crescentyr--card.png"
  },
  "knobback": {
    "internalId": 160,
    "cardAssetId": "monsterdex/cards/160--knobback--card.png"
  },
  "rampartail": {
    "internalId": 161,
    "cardAssetId": "monsterdex/cards/161--rampartail--card.png"
  },
  "forgeclub": {
    "internalId": 162,
    "cardAssetId": "monsterdex/cards/162--forgeclub--card.png"
  },
  "hummcrest": {
    "internalId": 163,
    "cardAssetId": "monsterdex/cards/163--hummcrest--card.png"
  },
  "resonadon": {
    "internalId": 164,
    "cardAssetId": "monsterdex/cards/164--resonadon--card.png"
  },
  "voltchorus": {
    "internalId": 165,
    "cardAssetId": "monsterdex/cards/165--voltchorus--card.png"
  },
  "dustsnout": {
    "internalId": 166,
    "cardAssetId": "monsterdex/cards/166--dustsnout--card.png"
  },
  "bellroam": {
    "internalId": 167,
    "cardAssetId": "monsterdex/cards/167--bellroam--card.png"
  },
  "echonaris": {
    "internalId": 168,
    "cardAssetId": "monsterdex/cards/168--echonaris--card.png"
  },
  "tapshade": {
    "internalId": 169,
    "cardAssetId": "monsterdex/cards/169--tapshade--card.png"
  },
  "knucklemurmur": {
    "internalId": 170,
    "cardAssetId": "monsterdex/cards/170--knucklemurmur--card.png"
  },
  "hexfinger": {
    "internalId": 171,
    "cardAssetId": "monsterdex/cards/171--hexfinger--card.png"
  },
  "stridestamp": {
    "internalId": 172,
    "cardAssetId": "monsterdex/cards/172--stridestamp--card.png"
  },
  "quillmarshal": {
    "internalId": 173,
    "cardAssetId": "monsterdex/cards/173--quillmarshal--card.png"
  },
  "serpentjudge": {
    "internalId": 174,
    "cardAssetId": "monsterdex/cards/174--serpentjudge--card.png"
  },
  "spinewry": {
    "internalId": 175,
    "cardAssetId": "monsterdex/cards/175--spinewry--card.png"
  },
  "thornmirage": {
    "internalId": 176,
    "cardAssetId": "monsterdex/cards/176--thornmirage--card.png"
  },
  "kelpskein": {
    "internalId": 177,
    "cardAssetId": "monsterdex/cards/177--kelpskein--card.png"
  },
  "wraithfrond": {
    "internalId": 178,
    "cardAssetId": "monsterdex/cards/178--wraithfrond--card.png"
  },
  "prismjab": {
    "internalId": 179,
    "cardAssetId": "monsterdex/cards/179--prismjab--card.png"
  },
  "caviclub": {
    "internalId": 180,
    "cardAssetId": "monsterdex/cards/180--caviclub--card.png"
  },
  "spectrafist": {
    "internalId": 181,
    "cardAssetId": "monsterdex/cards/181--spectrafist--card.png"
  },
  "duneskip": {
    "internalId": 182,
    "cardAssetId": "monsterdex/cards/182--duneskip--card.png"
  },
  "springarc": {
    "internalId": 183,
    "cardAssetId": "monsterdex/cards/183--springarc--card.png"
  },
  "needlesnout": {
    "internalId": 184,
    "cardAssetId": "monsterdex/cards/184--needlesnout--card.png"
  },
  "riftrostrum": {
    "internalId": 185,
    "cardAssetId": "monsterdex/cards/185--riftrostrum--card.png"
  },
  "starburrow": {
    "internalId": 186,
    "cardAssetId": "monsterdex/cards/186--starburrow--card.png"
  },
  "sensecrown": {
    "internalId": 187,
    "cardAssetId": "monsterdex/cards/187--sensecrown--card.png"
  },
  "clearcroak": {
    "internalId": 188,
    "cardAssetId": "monsterdex/cards/188--clearcroak--card.png"
  },
  "vitrawisp": {
    "internalId": 189,
    "cardAssetId": "monsterdex/cards/189--vitrawisp--card.png"
  },
  "rootsnuff": {
    "internalId": 190,
    "cardAssetId": "monsterdex/cards/190--rootsnuff--card.png"
  },
  "termibreak": {
    "internalId": 191,
    "cardAssetId": "monsterdex/cards/191--termibreak--card.png"
  },
  "scenttail": {
    "internalId": 192,
    "cardAssetId": "monsterdex/cards/192--scenttail--card.png"
  },
  "nightvine": {
    "internalId": 193,
    "cardAssetId": "monsterdex/cards/193--nightvine--card.png"
  },
  "velvetstripe": {
    "internalId": 194,
    "cardAssetId": "monsterdex/cards/194--velvetstripe--card.png"
  },
  "glyphneck": {
    "internalId": 195,
    "cardAssetId": "monsterdex/cards/195--glyphneck--card.png"
  },
  "mangroknob": {
    "internalId": 196,
    "cardAssetId": "monsterdex/cards/196--mangroknob--card.png"
  },
  "baritonose": {
    "internalId": 197,
    "cardAssetId": "monsterdex/cards/197--baritonose--card.png"
  },
  "umbrelloom": {
    "internalId": 198,
    "cardAssetId": "monsterdex/cards/198--umbrelloom--card.png"
  },
  "abyssbell": {
    "internalId": 199,
    "cardAssetId": "monsterdex/cards/199--abyssbell--card.png"
  },
  "epochshield": {
    "internalId": 200,
    "cardAssetId": "monsterdex/cards/200--epochshield--card.png"
  },
  "simiri": {
    "internalId": 201,
    "cardAssetId": "monsterdex/cards/201--simiri--card.png"
  },
  "cinderimi": {
    "internalId": 202,
    "cardAssetId": "monsterdex/cards/202--cinderimi--card.png"
  },
  "brookimi": {
    "internalId": 203,
    "cardAssetId": "monsterdex/cards/203--brookimi--card.png"
  },
  "bramblemi": {
    "internalId": 204,
    "cardAssetId": "monsterdex/cards/204--bramblemi--card.png"
  },
  "voltimiri": {
    "internalId": 205,
    "cardAssetId": "monsterdex/cards/205--voltimiri--card.png"
  },
  "rimeiri": {
    "internalId": 206,
    "cardAssetId": "monsterdex/cards/206--rimeiri--card.png"
  },
  "omeniri": {
    "internalId": 207,
    "cardAssetId": "monsterdex/cards/207--omeniri--card.png"
  },
  "noctimiri": {
    "internalId": 208,
    "cardAssetId": "monsterdex/cards/208--noctimiri--card.png"
  },
  "alloymiri": {
    "internalId": 209,
    "cardAssetId": "monsterdex/cards/209--alloymiri--card.png"
  },
  "oraciri": {
    "internalId": 210,
    "cardAssetId": "monsterdex/cards/210--oraciri--card.png"
  },
  "aurevine": {
    "internalId": 211,
    "cardAssetId": "monsterdex/cards/211--aurevine--card.png"
  },
  "tempestyr": {
    "internalId": 212,
    "cardAssetId": "monsterdex/cards/212--tempestyr--card.png"
  },
  "brookotl": {
    "internalId": 213,
    "cardAssetId": "monsterdex/cards/213--brookotl--card.png"
  },
  "joltmeer": {
    "internalId": 214,
    "cardAssetId": "monsterdex/cards/214--joltmeer--card.png"
  },
  "voltbrace": {
    "internalId": 215,
    "cardAssetId": "monsterdex/cards/215--voltbrace--card.png"
  },
  "tempestark": {
    "internalId": 216,
    "cardAssetId": "monsterdex/cards/216--tempestark--card.png"
  },
  "rimeket": {
    "internalId": 217,
    "cardAssetId": "monsterdex/cards/217--rimeket--card.png"
  },
  "duskrime": {
    "internalId": 218,
    "cardAssetId": "monsterdex/cards/218--duskrime--card.png"
  },
  "nocthyrme": {
    "internalId": 219,
    "cardAssetId": "monsterdex/cards/219--nocthyrme--card.png"
  },
  "hailhorn": {
    "internalId": 220,
    "cardAssetId": "monsterdex/cards/220--hailhorn--card.png"
  },
  "gloamfawn": {
    "internalId": 221,
    "cardAssetId": "monsterdex/cards/221--gloamfawn--card.png"
  },
  "emberrook": {
    "internalId": 222,
    "cardAssetId": "monsterdex/cards/222--emberrook--card.png"
  },
  "veilpaca": {
    "internalId": 223,
    "cardAssetId": "monsterdex/cards/223--veilpaca--card.png"
  },
  "steelstork": {
    "internalId": 224,
    "cardAssetId": "monsterdex/cards/224--steelstork--card.png"
  },
  "amberruptor": {
    "internalId": 225,
    "cardAssetId": "monsterdex/cards/225--amberruptor--card.png"
  },
  "fernplate": {
    "internalId": 226,
    "cardAssetId": "monsterdex/cards/226--fernplate--card.png"
  },
  "hoornvault": {
    "internalId": 227,
    "cardAssetId": "monsterdex/cards/227--hoornvault--card.png"
  },
  "tidespine": {
    "internalId": 228,
    "cardAssetId": "monsterdex/cards/228--tidespine--card.png"
  },
  "pillarneck": {
    "internalId": 229,
    "cardAssetId": "monsterdex/cards/229--pillarneck--card.png"
  },
  "shadejackal": {
    "internalId": 230,
    "cardAssetId": "monsterdex/cards/230--shadejackal--card.png"
  },
  "frostbasil": {
    "internalId": 231,
    "cardAssetId": "monsterdex/cards/231--frostbasil--card.png"
  },
  "terradrake": {
    "internalId": 232,
    "cardAssetId": "monsterdex/cards/232--terradrake--card.png"
  },
  "abysswyrm": {
    "internalId": 233,
    "cardAssetId": "monsterdex/cards/233--abysswyrm--card.png"
  },
  "umbralisk": {
    "internalId": 234,
    "cardAssetId": "monsterdex/cards/234--umbralisk--card.png"
  },
  "scarabrex": {
    "internalId": 235,
    "cardAssetId": "monsterdex/cards/235--scarabrex--card.png"
  },
  "warmaw": {
    "internalId": 236,
    "cardAssetId": "monsterdex/cards/236--warmaw--card.png"
  },
  "hearthscale": {
    "internalId": 237,
    "cardAssetId": "monsterdex/cards/237--hearthscale--card.png"
  },
  "moonjackal": {
    "internalId": 238,
    "cardAssetId": "monsterdex/cards/238--moonjackal--card.png"
  },
  "petalnix": {
    "internalId": 239,
    "cardAssetId": "monsterdex/cards/239--petalnix--card.png"
  },
  "starimp": {
    "internalId": 240,
    "cardAssetId": "monsterdex/cards/240--starimp--card.png"
  },
  "lullacorn": {
    "internalId": 241,
    "cardAssetId": "monsterdex/cards/241--lullacorn--card.png"
  },
  "wispmoth": {
    "internalId": 242,
    "cardAssetId": "monsterdex/cards/242--wispmoth--card.png"
  },
  "tidebelle": {
    "internalId": 243,
    "cardAssetId": "monsterdex/cards/243--tidebelle--card.png"
  },
  "gleamgoyle": {
    "internalId": 244,
    "cardAssetId": "monsterdex/cards/244--gleamgoyle--card.png"
  }
} as const;
