import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { interactiveMaps } from "../src/content/maps.ts";
import { content } from '../src/content/index.ts';
import { NATIVE_BATTLE_ASSET_ROOT, NATIVE_SPRITE_ALIASES } from '../src/content/battle-assets.ts';

// Static requires let Metro bundle the actual local PNGs without network dependencies.
const lines: string[] = [];
for (const map of interactiveMaps) {
  // Old continent sources still contain retired city names. Use the approved network overview.
  const assetId = map.level === 'continent' ? 'maps/continents/continent--exchange-network--world-map' : map.assetId;
  if (!assetId || !existsSync(`assets/pixel/${assetId}.png`)) continue;
  lines.push(`  ${JSON.stringify(map.id)}: require(${JSON.stringify(`../assets/pixel/${assetId}.png`)}),`);
}
const manifest = JSON.parse(readFileSync(`${NATIVE_BATTLE_ASSET_ROOT}/sprites.json`, "utf8"));
const sprites = manifest.lines.flatMap((line: { monsters: { id: string }[] }) => line.monsters).flatMap((monster: { id: string }) => {
  const id = NATIVE_SPRITE_ALIASES[monster.id] ?? monster.id;
  if (!content.species.some(species => species.id === id)) { console.log(`Unassigned sprite retained: ${monster.id}`); return []; }
  return [`  ${JSON.stringify(id)}: require(${JSON.stringify(`../${NATIVE_BATTLE_ASSET_ROOT}/sprites/256/${monster.id}/idle.png`)}),`];
});
mkdirSync("mobile", { recursive: true });
writeFileSync("mobile/assets.ts", `// Generated by scripts/build-native-assets.ts\nimport type { ImageSourcePropType } from 'react-native';\nexport const maps: Record<string, ImageSourcePropType> = {\n${lines.join("\n")}\n};\nexport const sprites: Record<string, ImageSourcePropType> = {\n${sprites.join("\n")}\n};\n`);
console.log(`Native assets: ${lines.length} maps, ${sprites.length} monster portraits.`);
