const positions=[[50,18],[26,30],[74,30],[18,52],[50,45],[82,52],[28,72],[56,72],[78,78],[50,88]];
const city=(name,region,regionId,continent,role,image,facilities)=>({name,region,regionId,continent,role,image,facilities:facilities.map((facility,index)=>[...facility,...positions[index]])});
const cities={
  "rimegate":city("Rimegate","Frostmarch","frostmarch","Ardenfall","Caravan city at the glacier roads.","city--rimegate--map.png",[["aurora-observatory","Aurora Observatory","unique"],["rime-exchange","Rime Exchange","market"],["white-road-arena","White Road Arena","arena"],["hearth-inn","Hearth Inn","inn"],["cold-vault","Cold Vault","storage"],["sled-terminal","Sled & Coach Terminal","transport"],["climate-station","Climate Station","research"],["frost-pens","Frost Pens","breeding"],["coldforge-hall","Coldforge Hall","craft"]]),
  "thunderrest":city("Thunderrest","Stormpeak","stormpeak","Ardenfall","High-altitude city controlling the mountain passes.","city--thunderrest--map.png",[["weather-beacon","Weather Beacon","unique"],["storm-exchange","Storm Exchange","market"],["thunder-crown-arena","Thunder Crown Arena","arena"],["peak-lodge","Peak Lodge","inn"],["storm-vault","Storm Vault","storage"],["skyrail-terminal","Skyrail Terminal","transport"],["resonance-station","Resonance Station","research"],["cliff-roosts","Cliff Roosts","breeding"],["coil-workshop","Coil Workshop","craft"]]),
  "willowmere":city("Willowmere","Greenreach","greenreach","Ardenfall","Starting market town and agricultural ecology center.","city--willowmere--map.png",[["orchard-registry","Orchard Registry","unique"],["willow-exchange","Willow Exchange","market"],["orchard-trial-arena","Orchard Trial Arena","arena"],["willow-inn","Willow Inn","inn"],["keepers-vault","Keeper's Vault","storage"],["coach-yard","Coach Yard","transport"],["field-ecology-desk","Field Ecology Desk","research"],["pasture-nursery","Pasture Nursery","breeding"],["craft-lodge","Craft Lodge","craft"]]),
  "cairnstead":city("Cairnstead","Stonehollow","stonehollow","Ardenfall","Quarry city and mineral trade center.","city--cairnstead--map.png",[["survey-guild","Survey Guild","unique"],["stone-exchange","Stone Exchange","market"],["faultline-arena","Faultline Arena","arena"],["cairn-rest","Cairn Rest","inn"],["deepcell-vault","Deepcell Vault","storage"],["oreline-station","Oreline Station","transport"],["geology-annex","Geology Annex","research"],["burrow-pens","Burrow Pens","breeding"],["forge-cooperative","Forge Cooperative","craft"]]),
  "ferrum-gate":city("Ferrum Gate","Iron Dominion","iron-dominion","Ardenfall","Industrial metropolis and continental logistics gateway.","city--ferrum-gate--map.png",[["freight-futures-board","Freight Futures Board","unique"],["ferrum-exchange","Ferrum Exchange","market"],["foundry-crucible","Foundry Crucible","arena"],["railmans-rest","Railman's Rest","inn"],["iron-vault","Iron Vault","storage"],["continental-hub","Continental Rail & Airship Hub","transport"],["industrial-research-bureau","Industrial Research Bureau","research"],["works-pens","Works Pens","breeding"],["foundry-complex","Foundry Complex","craft"]]),
  "crownspire":city("Crownspire","Aurelia","aurelia","Ardenfall","Continental capital and financial center.","city--crownspire--map.png",[["grand-exchange-floor","Grand Exchange Floor","unique"],["crown-exchange","Crown Exchange","market"],["crown-exhibition-arena","Crown Exhibition Arena","arena"],["grand-crown-inn","Grand Crown Inn","inn"],["royal-menagerie-vault","Royal Menagerie Vault","storage"],["central-transit-concourse","Central Transit Concourse","transport"],["royal-research-institute","Royal Research Institute","research"],["pedigree-court","Pedigree Court","breeding"],["artisan-quarter","Artisan Quarter","craft"]]),
  "tidemark":city("Tidemark","Mistwater Coast","mistwater-coast","Ardenfall","Harbor city and capture-shipping center.","city--tidemark--map.png",[["auction-pier","Auction Pier","unique"],["tidemark-exchange","Tidemark Exchange","market"],["tideglass-arena","Tideglass Arena","arena"],["harbor-inn","Harbor Inn","inn"],["tidepens","Tidepens","storage"],["grand-harbor","Grand Harbor","transport"],["marine-field-lab","Marine Field Lab","research"],["reef-hatchery","Reef Hatchery","breeding"],["dockworks","Dockworks","craft"]]),
  "fenwatch":city("Fenwatch","Mirefen","mirefen","Ardenfall","Raised swamp city focused on ecology enforcement.","city--fenwatch--map.png",[["conservation-office","Conservation Office","unique"],["fen-exchange","Fen Exchange","market"],["drowned-grove-arena","Drowned Grove Arena","arena"],["lantern-inn","Lantern Inn","inn"],["stilt-vault","Stilt Vault","storage"],["causeway-depot","Causeway Depot","transport"],["wetland-lab","Wetland Lab","research"],["bog-nursery","Bog Nursery","breeding"],["apothecary-works","Apothecary Works","craft"]]),
  "ashenhold":city("Ashenhold","Dragonspine","dragonspine","Veydris","Fortified volcanic frontier city.","city--ashenhold--map.png",[["hunt-registry","Hunt Registry","unique"],["ashen-exchange","Ashen Exchange","market"],["ashen-relic-arena","Ashen Relic Arena","arena"],["cinder-lodge","Cinder Lodge","inn"],["basalt-vault","Basalt Vault","storage"],["expedition-gate","Expedition Gate","transport"],["fossil-volcanic-institute","Fossil & Volcanic Institute","research"],["ash-pens","Ash Pens","breeding"],["relic-forge","Relic Forge","craft"]]),
  "lumenfall":city("Lumenfall","Crystal Depths","crystal-depths","Veydris","Vertical cavern city and research capital.","city--lumenfall--map.png",[["archive-exchange","Archive Exchange","unique"],["lumen-exchange","Lumen Exchange","market"],["resonance-archive-arena","Resonance Archive Arena","arena"],["lumen-rest","Lumen Rest","inn"],["prism-vault","Prism Vault","storage"],["crystal-lift-nexus","Crystal Lift Nexus","transport"],["worldseam-institute","Worldseam Institute","research"],["resonance-nursery","Resonance Nursery","breeding"],["crystalworks","Crystalworks","craft"]]),
  "blacktide":city("Blacktide","The Deep","the-deep","Veydris","Pressure-sealed abyssal port.","city--blacktide--map.png",[["deep-auction-house","Deep Auction House","unique"],["blacktide-exchange","Blacktide Exchange","market"],["black-current-arena","Black Current Arena","arena"],["pressure-inn","Pressure Inn","inn"],["hadal-vault","Hadal Vault","storage"],["submersible-dock","Submersible Dock","transport"],["abyssal-lab","Abyssal Lab","research"],["pressure-pens","Pressure Pens","breeding"],["salvage-works","Salvage Works","craft"]]),
  "seamwatch":city("Seamwatch","The Rift","rift","Veydris","Containment city built around a stable Worldseam anchor.","city--seamwatch--map.png",[["worldseam-control","Worldseam Control","unique"],["seam-exchange","Seam Exchange","market"],["worldseam-arena","Worldseam Arena","arena"],["anchor-rest","Anchor Rest","inn"],["sealed-vault","Sealed Vault","storage"],["anomaly-transit-ring","Anomaly Transit Ring","transport"],["containment-institute","Containment Institute","research"],["restricted-nursery","Restricted Nursery","breeding"],["stabilizer-workshop","Stabilizer Workshop","craft"]]),
};
const requested=new URLSearchParams(location.search).get("city")??"willowmere";const current=cities[requested]??cities.willowmere;let selected=current.facilities[0][0];let query="";
const $=selector=>document.querySelector(selector);const byId=id=>current.facilities.find(facility=>facility[0]===id);const icon={unique:"✦",market:"◆",arena:"⚔",inn:"⌂",storage:"▣",transport:"⇄",research:"◇",breeding:"♡",craft:"⚒"};
const description={unique:"Signature city service",market:"Buy, sell, list, and inspect market trends",arena:"Challenges, tournaments, and regional trials",inn:"Rest, recover, and advance time",storage:"Manage owned monsters and teams",transport:"Regional and intercontinental travel",research:"Research species, ecology, and evolution",breeding:"Manage breeding and nursery capacity",craft:"Craft equipment and process materials"};
function button(facility,compact=false){const[id,name,kind,x,y]=facility;if(compact)return `<button class="destination ${id===selected?"selected":""}" data-facility="${id}" type="button"><span>${icon[kind]}</span><span><span class="name">${name}</span><small>${kind}</small></span></button>`;return `<button class="facility-hotspot ${id===selected?"selected":""}" data-facility="${id}" style="left:${x}%;top:${y}%" type="button" aria-label="${name}">${icon[kind]}</button><span class="facility-label" style="left:${x}%;top:${y}%">${name}</span>`;}
function render(){const facility=byId(selected);const visible=current.facilities.filter(item=>`${item[1]} ${item[2]}`.toLowerCase().includes(query));$("#pageTitle").textContent=current.name;$("#continentCrumb").textContent=current.continent;$("#regionCrumb").textContent=current.region;$("#regionCrumb").href=`/prototype/world-map/region-map.html?region=${current.regionId}`;$("#cityCrumb").textContent=current.name;$("#cityImage").src=`/assets/pixel/maps/cities/${current.image}`;$("#cityImage").alt=`Interactive pixel-art city map of ${current.name}`;$("#facilityList").innerHTML=visible.map(item=>button(item,true)).join("")||`<p class="region-description">No matching facilities.</p>`;$("#facilityHotspotLayer").innerHTML=current.facilities.map(item=>button(item)).join("");$("#facilityIcon").textContent=icon[facility[2]];$("#facilityKind").textContent=facility[2];$("#facilityName").textContent=facility[1];$("#cityRole").textContent=current.role;$("#facilityCity").textContent=current.name;$("#facilityRegion").textContent=current.region;$("#facilityService").textContent=description[facility[2]];$("#facilitySummary").textContent=`${description[facility[2]]}. This hotspot is ready to connect to the corresponding game system.`;$("#backToRegion").href=`/prototype/world-map/region-map.html?region=${current.regionId}`;}
document.addEventListener("click",event=>{const target=event.target.closest("[data-facility]");if(target){selected=target.dataset.facility;render();}});
$("#facilitySearch").addEventListener("input",event=>{query=event.target.value.trim().toLowerCase();render();});
$("#facilityAction").addEventListener("click",()=>{
  const facility=byId(selected);
  if(facility[2]==="arena"){location.href="/prototype/battle/";return;}
  if(facility[2]==="transport"){location.href="/prototype/world-map/";return;}
  if(facility[2]==="research"){location.href="/prototype/monsterdex/";return;}
  const toast=$("#toast");toast.textContent=`${facility[1]}: this service is not playable yet.`;
  toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),1800);
});render();
