const regions={
  "frostmarch":{name:"Frostmarch",icon:"❄",image:"region--frostmarch--map.png",description:"Tundra, frozen lakes, pine valleys, and glacier foothills.",neighbors:[["Greenreach","land border"],["Stonehollow","land border"],["Stormpeak","rail border"]],sites:[
    ["aurora-shelf","Aurora Shelf","expedition",68,18,"Survey an aurora-lit expedition shelf."],["aurora-markers","Aurora Markers","landmark",73,24,"Ancient markers track the northern lights."],["whitebarrow","Whitebarrow","landmark",47,34,"A snowbound barrow beside Aurora Pass."],["glacial-mere","Glacial Mere","landmark",26,39,"A frozen lake along the Icewatch route."],["white-road-arena","White Road Arena","arena",55,50,"Frostmarch's regional combat trial."],["rimegate","Rimegate","city",49,58,"The fortified capital and primary exchange hub."],["hearthpost","Hearthpost","settlement",60,63,"A warm caravan post below the glacier."],["pinewater","Pinewater","settlement",34,66,"A timber settlement beside meltwater pines."]]},
  "stormpeak":{name:"Stormpeak",icon:"ϟ",image:"region--stormpeak--map.png",description:"Storm cliffs, magnetic peaks, and cloud-wrapped high passes.",neighbors:[["Frostmarch","rail border"],["Stonehollow","land border"],["Iron Dominion","rail border"]],sites:[
    ["magnetspire-shelf","Magnetspire Shelf","expedition",42,24,"A charged shelf used for hazardous expeditions."],["highstep","Highstep","settlement",50,25,"A high-altitude pass settlement."],["skyglass-ridge","Skyglass Ridge","landmark",72,27,"A glassy ridge shaped by lightning."],["thunder-crown","Thunder Crown","arena",61,36,"Stormpeak's regional combat trial."],["gale-camp","Gale Camp","settlement",37,41,"A sheltered camp above the ravines."],["thunderrest","Thunderrest","city",52,57,"The mountain capital and rail exchange."],["coilwatch","Coilwatch","settlement",64,68,"A southern watch station on the iron route."]]},
  "greenreach":{name:"Greenreach",icon:"♧",image:"region--greenreach--map.png",description:"Rolling fields, orchard belts, river woods, and wetlands.",neighbors:[["Frostmarch","land border"],["Stonehollow","road border"],["Mistwater Coast","coastal route"]],sites:[
    ["mosswater-ford","Mosswater Ford","landmark",23,56,"A shallow crossing into the western woods."],["old-canopy-preserve","Old Canopy Preserve","expedition",30,34,"A protected old-growth expedition site."],["brookmead","Brookmead","settlement",37,62,"A meadow settlement beside the river."],["sunpetal-terraces","Sunpetal Terraces","landmark",41,45,"Flowering terraces above Willowmere."],["willowmere","Willowmere","city",46,55,"Greenreach's garden capital and starting exchange."],["applecross","Applecross","settlement",55,63,"An orchard crossroads east of the capital."],["orchard-crown","Orchard Crown","arena",60,44,"Greenreach's regional combat trial."],["reedbridge","Reedbridge","settlement",46,79,"The southern bridge toward Aurelia."]]},
  "stonehollow":{name:"Stonehollow",icon:"◆",image:"region--stonehollow--map.png",description:"Quarries, canyon shelves, mines, and broken stone roads.",neighbors:[["Frostmarch","land border"],["Stormpeak","land border"],["Greenreach","road border"],["Iron Dominion","rail border"],["Aurelia","rail border"]],sites:[
    ["broken-crown-quarry","Broken Crown Quarry","landmark",25,68,"A collapsed quarry on the western road."],["old-quarry-depths","Old Quarry Depths","expedition",31,57,"A deep expedition route below abandoned workings."],["splitpick","Splitpick","settlement",34,46,"A mining settlement at the road fork."],["greycap","Greycap","settlement",44,18,"A northern settlement beneath the ridge."],["cairnstead","Cairnstead","city",51,46,"The stone capital and mineral exchange."],["faultline-amphitheatre","Faultline Amphitheatre","arena",57,31,"Stonehollow's regional combat trial."],["echo-gulch","Echo Gulch","landmark",65,37,"A resonant canyon leading east."],["ore-hollow","Ore Hollow","settlement",71,55,"An ore town near the Dominion border."]]},
  "iron-dominion":{name:"Iron Dominion",icon:"⚙",image:"region--iron-dominion--map.png",description:"Foundries, rail yards, industrial canals, and slag fields.",neighbors:[["Stormpeak","rail border"],["Stonehollow","rail border"],["Aurelia","road border"],["Mirefen","rail border"]],sites:[
    ["old-slagworks","Old Slagworks","expedition",31,63,"An abandoned industrial expedition complex."],["ferrum-gate","Ferrum Gate","city",48,44,"The industrial capital and rail exchange."],["foundry-crucible","Foundry Crucible","arena",55,36,"The Dominion's regional combat trial."],["scrapline-yard","Scrapline Yard","landmark",24,48,"A sprawling salvage and rail yard."],["foundry-canal","Foundry Canal","landmark",65,52,"A lock-controlled industrial waterway."],["slagfield-expanse","Slagfield Expanse","landmark",72,68,"Cooling slag plains along the southern route."]]},
  "aurelia":{name:"Aurelia",icon:"☀",image:"region--aurelia--map.png",description:"River plains, royal woods, and Ardenfall's dense urban trade belt.",neighbors:[["Stonehollow","rail border"],["Greenreach","royal road"],["Mistwater Coast","ferry route"],["Mirefen","causeway border"],["Iron Dominion","rail border"]],sites:[
    ["royal-preserve","Royal Preserve","expedition",31,29,"A licensed managed ecology expedition."],["preserve-gate","Preserve Gate","settlement",27,34,"Permit desk and ranger village."],["crownspire","Crownspire","city",52,48,"The continental capital and Grand Exchange."],["crown-exhibition-grounds","Crown Exhibition Grounds","arena",61,42,"Aurelia's championship trial grounds."],["goldbridge","Goldbridge","settlement",71,52,"The high-volume eastern freight corridor."],["sunmere","Sunmere","settlement",40,63,"A market town on the capital river road."],["sunstone-ruins","Sunstone Ruins","landmark",52,73,"A reusable field-research landmark."],["exhibition-warehouse","Exhibition Warehouse","landmark",77,35,"A suspicious auction-supply story site."]]},
  "mistwater-coast":{name:"Mistwater Coast",icon:"⚓",image:"region--mistwater-coast--map.png",description:"Coastal bays, tidal marshes, reef shelves, and river mouths.",neighbors:[["Greenreach","coastal road"],["Mirefen","tidal border"],["Aurelia","ferry route"]],sites:[
    ["moonpool-cay","Moonpool Cay","landmark",16,78,"A moon-tide rare ecology site."],["reefhome","Reefhome","settlement",28,66,"A fishing village supporting legal reef capture."],["reefward-shelf","Reefward Shelf","expedition",29,69,"The primary reef expedition entrance."],["gullwatch","Gullwatch","settlement",35,43,"A safe harbor checkpoint and ferry stop."],["tidemark","Tidemark","city",48,54,"The harbor capital and capture-shipping center."],["tideglass-ring","Tideglass Ring","arena",57,43,"Mistwater's regional combat trial."],["saltbridge","Saltbridge","settlement",67,35,"A river-and-coast trading junction."],["sunken-holding-pens","Sunken Holding Pens","landmark",74,61,"An illegal-supply investigation site."]]},
  "mirefen":{name:"Mirefen",icon:"♨",image:"region--mirefen--map.png",description:"Swamps, drowned woods, fungal wetlands, and raised causeways.",neighbors:[["Greenreach","wetland border"],["Mistwater Coast","tidal border"],["Aurelia","causeway border"],["Iron Dominion","drainage border"]],sites:[
    ["bait-pen-ruins","Bait-Pen Ruins","landmark",27,31,"A rescue and evidence site in the north wetlands."],["blackroot-wetlands","Blackroot Wetlands","expedition",29,51,"The primary Poison and Ghost expedition."],["reedhollow","Reedhollow","settlement",38,39,"A raised medicinal-material village."],["fenwatch","Fenwatch","city",54,43,"The conservation capital and regional exchange."],["drowned-grove-ring","Drowned Grove Ring","arena",43,62,"Mirefen's regional combat trial."],["lanternwick","Lanternwick","settlement",63,59,"A night-active town with breeder services."],["wispfen-shrine","Wispfen Shrine","landmark",59,72,"A quiet Bond and ecology landmark."],["sluice-end","Sluice End","settlement",80,45,"An industrial drainage hamlet at the Dominion border."]]},
  "dragonspine":{name:"Dragonspine",icon:"♨",image:"region--dragonspine--map.png",description:"Volcanoes, ash forests, obsidian ridges, and fossil badlands.",neighbors:[["Crystal Depths","fault border"],["The Deep","abyss border"]],sites:[
    ["fossil-gravefield","Fossil Gravefield","landmark",28,31,"A permit-only fossil rare-hunt site."],["fossil-camp","Fossil Camp","settlement",28,35,"A controlled research and hunt camp."],["cinderpost","Cinderpost","settlement",34,58,"A frontier safety stop and material market."],["emberbone-ravine","Emberbone Ravine","expedition",37,72,"The primary volcanic expedition route."],["ashenhold","Ashenhold","city",45,50,"Veydris's fortified volcanic frontier city."],["ashen-relic-ring","Ashen Relic Ring","arena",55,44,"Dragonspine's regional combat trial."],["ashglass-excavation","Ashglass Excavation","landmark",63,27,"A controlled fossil-evidence site."],["prismwatch","Prismwatch","settlement",72,42,"A fault-monitoring outpost at the crystal border."]]},
  "crystal-depths":{name:"Crystal Depths",icon:"◇",image:"region--crystal-depths--map.png",description:"Crystal caverns, luminous lakes, and ancient resonance ruins.",neighbors:[["Dragonspine","fault border"],["The Rift","fracture border"],["The Deep","cavern edge"]],sites:[
    ["echo-caverns","Echo Caverns","expedition",29,58,"The primary crystal-cavern expedition."],["memory-gallery","Memory Gallery","landmark",34,26,"A special-evolution knowledge landmark."],["facet-hollow","Facet Hollow","settlement",38,56,"A crafting and breeding cavern town."],["resonance-archive","Resonance Archive","arena",51,38,"Crystal Depths' regional combat trial."],["lumenfall","Lumenfall","city",54,48,"The vertical research capital of Veydris."],["archive-steps","Archive Steps","settlement",56,30,"A vertical archive-route hamlet."],["echo-ward","Echo Ward","settlement",66,61,"A resonance research settlement."],["mirror-lake","Mirror Lake","landmark",73,47,"A reusable reflection and ecology puzzle site."]]},
  "the-deep":{name:"The Deep",icon:"≋",image:"region--the-deep--map.png",description:"Abyssal shelves, blackwater ruins, trenches, and pressure caverns.",neighbors:[["Dragonspine","abyss border"],["The Rift","current border"],["Crystal Depths","cavern edge"]],sites:[
    ["hadal-rift-mouth","Hadal Rift Mouth","landmark",27,75,"A research-gated abyssal rare-hunt site."],["hadal-mooring","Hadal Mooring","settlement",35,70,"A submersible launch outpost."],["drowned-observatory","Drowned Observatory","expedition",42,66,"The primary abyss research expedition."],["blacktide","Blacktide","city",46,40,"A pressure-sealed abyssal port and rare auction hub."],["blacktide-arena","Blacktide Arena","arena",54,33,"The Deep's regional combat trial."],["pressure-rest","Pressure Rest","settlement",54,55,"A safe recovery and freight settlement."],["lanternless-quay","Lanternless Quay","settlement",67,37,"A thin-market salvage hamlet."],["ancient-current-beacon","Ancient Current Beacon","landmark",72,72,"A world-state current stabilization site."]]},
  "rift":{name:"The Rift",icon:"◉",image:"region--rift--map.png",description:"Floating shards, void marshes, fractured ruins, and gravity tears.",neighbors:[["Crystal Depths","fracture border"],["The Deep","current border"]],sites:[
    ["adaptive-route-field","Adaptive Route Field","landmark",22,54,"A dynamic route-selection encounter field."],["fracture-marsh","Fracture Marsh","expedition",28,68,"The primary anomaly expedition."],["fracture-post","Fracture Post","settlement",31,43,"A shifting-route survey outpost."],["worldseam-trial-ring","Worldseam Trial Ring","arena",49,42,"The Rift's endgame combat trial."],["seamwatch","Seamwatch","city",50,54,"The containment city built around a stable anchor."],["anchor-camp","Anchor Camp","settlement",44,61,"A semi-permanent anomaly response base."],["surveyors-rest","Surveyor's Rest","settlement",64,34,"A high-tier research hamlet."],["guardian-verge","Guardian Verge","landmark",73,58,"A protected guardian-observation site."]]},
};
const requested=new URLSearchParams(location.search).get("region")??"greenreach";
const region=regions[requested]??regions.greenreach; let selected=region.sites.find(site=>site[2]==="city")?.[0]??region.sites[0][0];
const $=s=>document.querySelector(s),siteById=id=>region.sites.find(site=>site[0]===id);
const glyph={city:"◆",settlement:"●",arena:"⚔",expedition:"✦",landmark:"◇"};
const veydrisRegions=new Set(["dragonspine","crystal-depths","the-deep","rift"]);
const regionId=name=>name==="The Rift"?"rift":name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
function siteButton(site,compact=false){const[id,name,kind,x,y]=site;if(compact)return `<button class="destination ${id===selected?"selected":""}" data-site="${id}" type="button"><span>${glyph[kind]}</span><span><span class="name">${name}</span><small>${kind}</small></span></button>`;return `<button class="site-hotspot ${id===selected?"selected":""}" data-kind="${kind}" data-site="${id}" style="left:${x}%;top:${y}%" type="button" aria-label="${name}">${glyph[kind]}</button><span class="site-label" style="left:${x}%;top:${y}%">${name}</span>`;}
function routes(){const center=region.sites.find(site=>site[2]==="city")??region.sites[0];return region.sites.filter(site=>site!==center).map(site=>`<line class="region-route" x1="${center[3]*10}" y1="${center[4]*6.67}" x2="${site[3]*10}" y2="${site[4]*6.67}"/>`).join("");}
function render(){const site=siteById(selected),continent=veydrisRegions.has(requested)?"Veydris":"Ardenfall";$("#pageTitle").textContent=region.name;$("#continentCrumb").textContent=continent;$("#regionCrumb").textContent=region.name;$("#regionImage").src=`/assets/pixel/maps/regions/${region.image}`;$("#regionImage").alt=`Interactive pixel-art navigation map of ${region.name}`;$("#siteList").innerHTML=region.sites.map(s=>siteButton(s,true)).join("");$("#siteHotspotLayer").innerHTML=region.sites.map(s=>siteButton(s)).join("");$("#regionRouteLayer").innerHTML=routes();$("#borderList").innerHTML=region.neighbors.map(([name,mode])=>`<a class="border-exit" href="/prototype/world-map/region-map.html?region=${regionId(name)}"><span>${name}</span><small>${mode} →</small></a>`).join("");$("#siteIcon").textContent=glyph[site[2]];$("#siteKind").textContent=site[2];$("#siteName").textContent=site[1];$("#siteDescription").textContent=site[5];$("#siteRegion").textContent=region.name;$("#siteFunction").textContent=site[2]==="city"?"Trade, heal, store & travel":site[2]==="arena"?"Regional trial":site[2]==="expedition"?"Exploration encounter":site[2]==="settlement"?"Rest & local trade":"Discovery site";$("#siteSummary").textContent=`${region.description} Select Open location to preview the ${site[2]} interaction.`;$("#siteAction").textContent=site[2]==="city"?"Enter city":site[2]==="arena"?"View trial":site[2]==="expedition"?"Start expedition":"Open location";}
document.addEventListener("click",event=>{const button=event.target.closest("[data-site]");if(button){selected=button.dataset.site;render();}});
$("#siteAction").addEventListener("click",()=>{const site=siteById(selected);if(site[2]==="city"){window.location.href=`/prototype/world-map/city-map.html?city=${site[0]}&region=${requested}`;return;}const toast=$("#toast");toast.textContent=`${site[1]} interaction selected`;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),1800);});
render();
